name: "PR Labeler"
on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: "Check PR title and add labels"
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            const labels = [];

            if (title.includes('bug')) {
              labels.push('bug');
            }
            if (title.includes('fix')) {
              labels.push('bug');
            }
            if (title.includes('duplicate')) {
              labels.push('duplicate');
            }
            if (title.includes('feature')) {
              labels.push('feature');
            }
            if (title.includes('support')) {
              labels.push('feature');
            }
            if (title.includes('good first issue')) {
              labels.push('good first issue');
            }
            if (title.includes('want to')) {
              labels.push('help wanted');
            }
            if (title.includes('invalid')) {
              labels.push('invalid');
            }
            if (title.includes('question')) {
              labels.push('question');
            }
            if (title.includes('wontfix')) {
              labels.push('wontfix');
            }
            if (title.includes('docs')) {
              labels.push('docs');
            }

            if (labels.length > 0) {
              const pr_number = context.payload.pull_request.number;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                labels: labels
              });
            }
