name: "PR Labeler"
on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: "Add labels based on PR title"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          labels: |
            bug
            duplicate
            feature
            good first issue
            help wanted
            invalid
            question
            wontfix
            docs
