name: Update chinesecalendar Version

on:
  workflow_dispatch:

jobs:
  update-chinesecalendar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: check latest version of chinesecalendar
        id: get_version
        run: |
          LATEST_VERSION=$(pip index versions chinesecalendar | grep 'AVAILABLE VERSIONS' | head -n1 | sed 's/.*: //;s/,.*//')
          if [ -z "$LATEST_VERSION" ]; then
            LATEST_VERSION=$(pip install chinesecalendar==randomstring 2>&1 | grep -oP 'from versions: \K.*' | cut -d, -f1)
          fi
          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: update chinesecalendar
        run: |
          pip install --upgrade chinesecalendar

      - name: sed chinesecalendar version in requirements.txt
        run: |
          if grep -q 'chinesecalendar==' requirements.txt; then
            sed -i "s/chinesecalendar==[0-9\.]\+/chinesecalendar==${{ steps.get_version.outputs.latest_version }}/" requirements.txt
          fi

      - name: sed chinesecalendar version in manifest.json
        run: |
          sed -i "s/\"chinesecalendar==[0-9\.]\+\"/\"chinesecalendar==${{ steps.get_version.outputs.latest_version }}\"/" custom_components/ha_vacation/manifest.json

      - name: check code changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add requirements.txt custom_components/ha_vacation/manifest.json
          git diff --cached --quiet || echo "changed=true" >> $GITHUB_ENV

      - name: commit and push to repo
        if: env.changed == 'true'
        run: |
          git commit -m "chore: update chinesecalendar version"
          git push
